# Site setings
name: 'Rosalyn'
description: "I'm a Software Engineer focused on developing Mobile Applications on the Android Platform."
meta_description: 'Jekyll template, minimal style, perfect for bloggers.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://horace.netlify.com/
disqus: 'justgoodthemes'
mailchimp_url:
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: 


# Author
author:
  name: 'Rosalyn Blanco'
  image: 'authorimage.jpg'
  greetings: 'Hola!'
  description: "My name is Rosalyn Blanco, and I'm an Android Developer based in Miami,FL. Welcome!"
  bio: "I'm a Software Engineer focused on developing Mobile Applications on the Android Platform."

# Contact form setings
email: rosalyn.blanco@gmail.com
contact_page_description: "Do you have any project on mind, or any question/suggestion? Feel free to reach out. If you prefer, at the bottom, you can find my social links to get in touch that way."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
github: 'rosebm'
linkedin: 'rosalynblanco'
twitter:
facebook:
codepen:
dribbble:
medium:
instagram:
pinterest:
producthunt: 

# Navigation
navigation:
  - text: About
    url: /about/
  - text: Projects
    url: /projects/
  - text: Contact Me
    url: /contact/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

